### GET request
GET http://localhost:8080/user-api/users


### GET user by id
GET http://localhost:8080/user-api/users/300

### POST request
POST http://localhost:8080/user-api/user
Content-Type: application/json

{
    "id":200,
    "name":"bhanu",
    "age":21
}


### PUT request
PUT http://localhost:8080/user-api/user
Content-Type: application/json

{
    "id":200,
    "name":"bhanu kumar",
    "age":25
}



### DELETE request
DELETE http://localhost:8080/user-api/user/100


### Req for product API
GET http://localhost:8080/product-api/products




# fetch(url,{
#     method:"POST:,
#     headers:{"Content-Type":"application/json"},
#     body:JSON.stringify(userObj)
# })