### GET request
GET http://localhost:8080/users


### GET user by id
GET http://localhost:8080/users/300

### POST request
POST http://localhost:8080/user
Content-Type: application/json

{
    "id":200,
    "name":"bhanu",
    "age":21
}


### PUT request
PUT http://localhost:8080/user
Content-Type: application/json

{
    "id":200,
    "name":"bhanu kumar",
    "age":25
}



### DELETE request
DELETE http://localhost:8080/user/100







# fetch(url,{
#     method:"POST:,
#     headers:{"Content-Type":"application/json"},
#     body:JSON.stringify(userObj)
# })